### ISSUE TITLE
Импорт старого формата object-файлов

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#153]
Нашёл object файл, который открывается в СДК, но не хочет импортироваться в блендер. Вот текст ошибки:
```Traceback (most recent call last):
  File "C:\Program Project\Blender Foundation\Blender 2.79\2.79\scripts\addons\io_scene_xray\plugin.py", line 15, in wrapper
    return method(self, context)
  File "C:\Program Project\Blender Foundation\Blender 2.79\2.79\scripts\addons\io_scene_xray\plugin.py", line 69, in execute
    import_file(os.path.join(self.directory, file.name), import_context)
  File "C:\Program Project\Blender Foundation\Blender 2.79\2.79\scripts\addons\io_scene_xray\log.py", line 13, in wrap
    return func(*args, **kwargs)
  File "C:\Program Project\Blender Foundation\Blender 2.79\2.79\scripts\addons\io_scene_xray\fmt_object_imp.py", line 788, in import_file
    _import(fpath, context, ChunkedReader(memoryview(file.read())))
  File "C:\Program Project\Blender Foundation\Blender 2.79\2.79\scripts\addons\io_scene_xray\fmt_object_imp.py", line 779, in _import
    _import_main(fpath, context, ChunkedReader(data))
  File "C:\Program Project\Blender Foundation\Blender 2.79\2.79\scripts\addons\io_scene_xray\fmt_object_imp.py", line 720, in _import_main
    mesh = _import_mesh(context, ChunkedReader(mdat), renamemap)
  File "C:\Program Project\Blender Foundation\Blender 2.79\2.79\scripts\addons\io_scene_xray\log.py", line 13, in wrap
    return func(*args, **kwargs)
  File "C:\Program Project\Blender Foundation\Blender 2.79\2.79\scripts\addons\io_scene_xray\fmt_object_imp.py", line 308, in _import_mesh
    images.append(bmat.active_texture.image)
AttributeError: 'NoneType' object has no attribute 'image'

location: <unknown location>:-1
```

Файл правда старый, за 2001 год. Вот он:
[det_asf1.zip](https://github.com/igelbox/blender-xray/files/1619525/det_asf1.zip)

**Comment by igelbox** [comment]
Там неизвестные для аддона чанки:
0x0905 - SURFACES
0x0914 - OMOTIONS
0x0918 - SURFACES_XRLC
0x1003 - NOT_USED_0
0x1011 - VMAPS_1
Получается, это бедут типа новая фича "Импорт старых форматов".

Но, может быть такие старые файлы уже никому не нужны. Тогда, у этой ишью - очень низкий приоритет. Если всё же нужны, то дайте знать.

**Comment by PavelBlend** [comment]
Я насчитал таких файлов более 100 штук. Они находятся в сливе исходников от GSC.
Может они никому и не нужны, но тогда нужно сделать так, чтобы плагин нормально обрабатывал импорт таких файлов. Чтобы не было ошибки, а было предупреждение. А то при batch импорте происходит остановка импорта из-за них.
