### ISSUE TITLE
Не экспортировать объекты без текстуры

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#160]
Если в блендере создать объект с UV, материалом, но без текстуры и экспортировать его в object, то экспорт пройдёт успешно и СДК такой объект откроет. А если импортировать данный object обратно в blender, то будет ошибка:
```Traceback (most recent call last):
  File "C:\Program Project\Blender Foundation\Blender 2.79\2.79\scripts\addons\io_scene_xray\plugin.py", line 16, in wrapper
    return method(self, context)
  File "C:\Program Project\Blender Foundation\Blender 2.79\2.79\scripts\addons\io_scene_xray\plugin.py", line 61, in execute
    import_file(os.path.join(self.directory, file.name), import_context)
  File "C:\Program Project\Blender Foundation\Blender 2.79\2.79\scripts\addons\io_scene_xray\log.py", line 13, in wrap
    return func(*args, **kwargs)
  File "C:\Program Project\Blender Foundation\Blender 2.79\2.79\scripts\addons\io_scene_xray\fmt_object_imp.py", line 746, in import_file
    _import(fpath, context, ChunkedReader(memoryview(file.read())))
  File "C:\Program Project\Blender Foundation\Blender 2.79\2.79\scripts\addons\io_scene_xray\fmt_object_imp.py", line 737, in _import
    _import_main(fpath, context, ChunkedReader(data))
  File "C:\Program Project\Blender Foundation\Blender 2.79\2.79\scripts\addons\io_scene_xray\fmt_object_imp.py", line 678, in _import_main
    mesh = _import_mesh(context, ChunkedReader(mdat), renamemap)
  File "C:\Program Project\Blender Foundation\Blender 2.79\2.79\scripts\addons\io_scene_xray\log.py", line 13, in wrap
    return func(*args, **kwargs)
  File "C:\Program Project\Blender Foundation\Blender 2.79\2.79\scripts\addons\io_scene_xray\fmt_object_imp.py", line 308, in _import_mesh
    images.append(bmat.active_texture.image)
AttributeError: 'NoneType' object has no attribute 'image'

location: <unknown location>:-1
```
Предложение: исправить данную ошибку (чтобы блендер мог такие объекты импортировать) и запретить плагину экспортировать объекты без текстур (вместо экспорта выводить предупреждение).

Вот пример такого object файла:
[Cube.zip](https://github.com/igelbox/blender-xray/files/1659145/Cube.zip)

**Comment by igelbox** [comment]
> запретить плагину экспортировать объекты без текстур

А зачем запрещать, если SDK успешно импортирует такие объекты? Может это кому-то пригодится.

**Comment by PavelBlend** [comment]
Хотя да. Это будет нужно, если кто-то захочет настроить текстуры в СДК, а не в блендере.
