### ISSUE TITLE
Ошибка при импорте stalker_animation.skls

### ISSUE THREAD

**Issue by IgeNiaI** [PavelBlend/blender-xray#191]
Я делаю одну игру в Unreal Engine 4 и решил использовать ресурсы из сталкера **Зов Припяти** (долго рассказывать зачем). Для этого мне нужно импортировать модели персонажей с анимациями.

Я разархивировал ресурсы игры (не помню через что, вспомню если понадобится), после чего конвертировал **.\meshes\actors\stalker_hero\stalker_hero_1.ogf** в .object через X-Ray Converter от Bardak, версия от 18 октября 2017 года. Модель импортируется в Blender нормально.
После конвертировал **.\meshes\actors\stalker_animation.omf** в **.skls** и при импорте получаю ошибку.

Аналогичные действия с **.\meshes\actors\bandits_animation.omf** ошибок не создают, все анимации импортируются нормально и дальше без ошибок попадают в UE4

> Traceback (most recent call last):
  File "C:\Users\Evghenii\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_xray\plugin.py", line 20, in wrapper
    return method(self, context)
  File "C:\Users\Evghenii\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_xray\plugin.py", line 313, in execute
    import_skls_file(fpath, import_context)
  File "C:\Users\Evghenii\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_xray\fmt_skl_imp.py", line 36, in import_skls_file
    import_motions(reader, context.armature, context.motions_filter)
  File "C:\Users\Evghenii\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_xray\xray_motions.py", line 122, in import_motions
    import_motion(reader, bpy_armature, bonesmap, reported, motions_filter)
  File "C:\Users\Evghenii\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_xray\log.py", line 13, in wrap
    return func(*args, **kwargs)
  File "C:\Users\Evghenii\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_xray\xray_motions.py", line 25, in import_motion
    skip = _skip_motion_rest(reader.getv(), 0)
  File "C:\Users\Evghenii\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_xray\xray_motions.py", line 152, in _skip_motion_rest
    ptr += (4 + 4) * fb.int_at(data, ptr - 4)
  File "C:\Users\Evghenii\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_xray\xray_io.py", line 11, in int_at
    return data[offs] | (data[offs + 1] << 8) | (data[offs + 2] << 16) | (data[offs + 3] << 24)
IndexError: index out of bounds on dimension 1
.
location: <unknown location>:-1

**Comment by PavelBlend** [comment]
Исправил ошибку. Можешь качать последний коммит из ветки develop и проверять на работоспособность. Если всё работает, то я закрою данный issues.

**Comment by IgeNiaI** [comment]
Теперь другая ошибка

> Traceback (most recent call last):
  File "C:\Users\Evghenii\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_xray\plugin.py", line 240, in draw
    row.label('%d items' % len(self.files))
  File "C:\Users\Evghenii\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_xray\plugin.py", line 278, in _get_motions
    if self.__parsed_file_name != fpath:
  File "C:\Users\Evghenii\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_xray\xray_motions.py", line 160, in examine_motions
    offs = 4
  File "C:\Users\Evghenii\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_xray\log.py", line 13, in wrap
    return func(*args, **kwargs)
  File "C:\Users\Evghenii\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_xray\xray_motions.py", line 128, in _examine_motion
    def _examine_motion(data, offs):
  File "C:\Users\Evghenii\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_xray\xray_motions.py", line 152, in _skip_motion_rest
    for _bone_idx in range(fb.int_at(data, ptr - 4)):
  File "C:\Users\Evghenii\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_xray\xray_io.py", line 11, in int_at
    return data[offs] | (data[offs + 1] << 8) | (data[offs + 2] << 16) | (data[offs + 3] << 24)
IndexError: index out of range
.
location: <unknown location>:-1

Ещё при попытке импорта отсутствует список "Filter Motions" для неработающих файлов.

**Comment by PavelBlend** [comment]
А эта другая ошибка появляется при импорте meshes\actors\stalker_animation? Я просто проверял и у меня нормально импортируется.

**Comment by IgeNiaI** [comment]
Да, при импорте этого файла. Как вы разархивировали ресурсы игры и как конвертировали .omf в .skls ? Сделаю так же чтоб откинуть другие варианты.

**Comment by PavelBlend** [comment]
А можешь скинуть твой skls. Я у себя импортирую.

**Comment by IgeNiaI** [comment]
[stalker_animation.zip](https://github.com/PavelBlend/blender-xray/files/2364427/stalker_animation.zip)

**Comment by PavelBlend** [comment]
У меня импортируется. А ты точно последний коммит скачал? Его надо скачивать кнопкой Clone or download:
https://github.com/PavelBlend/blender-xray/tree/0dd0c2aa092c246aa20c29334149cc607e49ae6c

**Comment by IgeNiaI** [comment]
Качал последний develop - не работало. Скачал по вашей ссылке - работает.
Спасибо.

**Comment by gameking-studio** [comment]
👋 Здравствуйте!

Я разрабатываю свою собственную игру под названием **The First One** — постапокалиптический приключенческий боевик на движке Unreal Engine 5.

🔹 ** Жанр:** Приключенческий боевик с открытым миром 
🔹 ** Сеттинг:** 3069 год, пустыня, руины, выживание 
🔹 ** Особенности: ** 3 игровых персонажа, уникальная механика смерти, кооперативный мультиплеер, экономика на DydoCoins 

Вы можете следить за развитием событий здесь: 
✅ [**MagaKaStoporom/TheFirstOne**](https://github.com/MagaKaStoporom/TheFirstOne/)

✅ Отметьте репозиторий, если вам нравится проект — это действительно помогает!

Спасибо за ваше внимание! 🙌
