### ISSUE TITLE
Создать оператор для проверки геометрии на наличие ошибок

### ISSUE THREAD

**Issue by 1az315456** [PavelBlend/blender-xray#305]
When i try to export as .ogf i will have this crash:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.82\scripts\addons\io_scene_xray\utils.py", line 442, in wrapper
    return method(self, context)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.82\scripts\addons\io_scene_xray\utils.py", line 454, in wrapper
    return func(self, context)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.82\scripts\addons\io_scene_xray\utils.py", line 463, in wrapper
    return method(self, context)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.82\scripts\addons\io_scene_xray\ogf\ops.py", line 43, in execute
    return self.export(roots[0], context)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.82\scripts\addons\io_scene_xray\ogf\ops.py", line 66, in export
    exp.export_file(bpy_obj, self.filepath, export_context)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.82\scripts\addons\io_scene_xray\ogf\exp.py", line 347, in export_file
    _export(bpy_obj, cwriter, context)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.82\scripts\addons\io_scene_xray\ogf\exp.py", line 278, in _export
    scan_r(bpy_obj)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.82\scripts\addons\io_scene_xray\ogf\exp.py", line 276, in scan_r
    scan_r(child)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.82\scripts\addons\io_scene_xray\ogf\exp.py", line 268, in scan_r
    _export_child(bpy_obj, mwriter, context, vgm)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.82\scripts\addons\io_scene_xray\ogf\exp.py", line 214, in _export_child
    pwriter.putf('HHH', face[0], face[2], face[1])
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.82\scripts\addons\io_scene_xray\xray_io.py", line 160, in putf
    self.data += struct.pack(fmt, *args)
struct.error: ushort format requires 0 <= number <= 0xffff

location: <unknown location>:-1

And when i try to export as .object it works, but when i load my object into the action editor my editor will crash with the following log:

FATAL ERROR
 
[error]Expression    : assertion failed
[error]Function      : x:\stalker_addon\sources\trunk\xrcore\FixedVector.h
[error]File          : x:\stalker_addon\sources\trunk\xrcore\FixedVector.h
[error]Line          : 38
[error]Description   : id<count

**Comment by PavelBlend** [comment]
Can you give your blend scene so that I can reproduce the error with myself?

**Comment by 1az315456** [comment]
I fixxed it, sorry for late response the problem was there being duplicate faces and deleting the .xr bad vertexes and duplicate faces solved the problem, if you want i can still send you the file to reproduce the error

**Comment by PavelBlend** [comment]
Yes, send me the file.

**Comment by 1az315456** [comment]
https://drive.google.com/file/d/1tBoeII9c_p-XzPu68UHnOnuef3_lNpT9/view?usp=sharing

**Comment by PavelBlend** [comment]
I am writing a note for myself:

Перезалил файл:
[special_ak74.zip](https://github.com/PavelBlend/blender-xray/files/4750200/special_ak74.zip)
Чтобы не потерять. Нужно либо выдавать предупреждения или ошибку при экспорте подобных мешей.

Хотя, придётся делать проверку на правильность площади полигонов при экспорте. А это замедлит экспорт. Лучше тогда сделать отдельно кнопку в интерфейсе для проверки.

**Comment by PavelBlend** [comment]
22c92e66684b4f20316b2cd9ff86b51822fa39c0
