### ISSUE TITLE
Невозможно экспортировать файл .object

### ISSUE THREAD

**Issue by Blackgrowl** [PavelBlend/blender-xray#448]
Я недавно обновился до Blender 3.0, использую последнюю версию PavelBlend 2.9.0, все работает отлично, кроме попытки импортировать .object файл (со "скелетом"), он выдает мне эту ошибку:

Python: Traceback (most recent call last):
  File "C:\Users\Strogglet\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\io_scene_xray\utils.py", line 461, in wrapper
    return method(self, context)
  File "C:\Users\Strogglet\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\io_scene_xray\utils.py", line 482, in wrapper
    return method(self, context)
  File "C:\Users\Strogglet\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\io_scene_xray\obj\exp\ops.py", line 242, in execute
    exp.export_file(bpy_obj, self.filepath, export_context)
  File "C:\Users\Strogglet\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\io_scene_xray\obj\exp\__init__.py", line 17, in export_file
    _export(bpy_obj, writer, context)
  File "C:\Users\Strogglet\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\io_scene_xray\obj\exp\__init__.py", line 11, in _export
    main.export_main(bpy_obj, writer, context)
  File "C:\Users\Strogglet\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\io_scene_xray\log.py", line 16, in wrap
    return func(*args, **kwargs)
  File "C:\Users\Strogglet\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\io_scene_xray\obj\exp\main.py", line 517, in export_main
    export_user_data(chunked_writer, xray)
  File "C:\Users\Strogglet\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\io_scene_xray\obj\exp\main.py", line 390, in export_user_data
    chunked_writer.put(
  File "C:\Users\Strogglet\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\io_scene_xray\xray_io.py", line 246, in put
    self.data += struct.pack('II', cid, len(writer.data))
AttributeError: 'NoneType' object has no attribute 'data'

location: <unknown location>:-1

В чем проблема?

**Comment by PavelBlend** [comment]
@Blackgrowl исправил. Эта ошибка появилась недавно, пару недель назад, когда я переписывал большую часть кода и кое-что недоглядел.

Фикс ошибки в новом релизе:
https://github.com/PavelBlend/blender-xray/releases/tag/v2.9.1
