### ISSUE TITLE
Ошибка, если в skls-браузере не указать файл

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#624]
Если не выбрать файл в skls браузере или указать несуществующий файл и нажать `Open .skls file`, то аддон выдаст ошибку:
```
Traceback (most recent call last):
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\io_scene_xray\ops\skls_browser.py", line 181, in execute
    init_skls_browser(self, context, self.filepath)
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\io_scene_xray\utils\__init__.py", line 77, in wrapper
    result = method(self, context, *args)
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\io_scene_xray\ops\skls_browser.py", line 85, in init_skls_browser
    skls = SklsFile(file_path=filepath)
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\io_scene_xray\ops\skls_browser.py", line 125, in __init__
    file_data = rw.utils.read_file(file_path)
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\io_scene_xray\rw\utils.py", line 25, in read_file
    raise log.AppError('No such file!')
io_scene_xray.log.AppError: No such file!
```

Нужно обрабатывать такой случай и показывать читаемое предупреждение.

**Comment by PavelBlend** [comment]
Теперь будут отображаться такие предупреждения:
![01](https://user-images.githubusercontent.com/7983249/233863491-97d56f1f-5c38-41bb-81d6-019fd8b41241.jpg)
![02](https://user-images.githubusercontent.com/7983249/233863496-cfd75cf1-47aa-47bf-b10f-7f1a8d692607.jpg)
