### ISSUE TITLE
Не работает Fit Shape, если кости назначена одна вершина

### ISSUE THREAD

**Issue by SamArtGit** [PavelBlend/blender-xray#651]
<details>
  <summary>Текст ошибки</summary>

```
Python: Traceback (most recent call last):
  File "C:\Users\artem\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_xray\ops\edit_helpers\bone_shape.py", line 88, in execute
    HELPER.activate(target)
  File "C:\Users\artem\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_xray\ops\edit_helpers\base.py", line 39, in activate
    self._update_helper(helper, target)
  File "C:\Users\artem\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_xray\ops\edit_helpers\bone_shape.py", line 53, in _update_helper
    bpy.ops.io_scene_xray.edit_bone_shape_fit()
  File "D:\Folders\Games\Steam\steamapps\common\Blender\3.6\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\artem\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_xray\ops\edit_helpers\bone_shape.py", line 221, in execute
    obb_mat = utils.bone.get_obb(bone, False)
  File "C:\Users\artem\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_xray\utils\bone.py", line 163, in get_obb
    obb_mat = generate_obb(verts_coord, for_cylinder)
  File "C:\Users\artem\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_xray\utils\bone.py", line 72, in generate_obb
    eig_vals, eig_vecs = numpy.linalg.eigh(cov_mat)
  File "<__array_function__ internals>", line 180, in eigh
  File "D:\Folders\Games\Steam\steamapps\common\Blender\3.6\python\lib\site-packages\numpy\linalg\linalg.py", line 1453, in eigh
    _assert_stacked_2d(a)
  File "D:\Folders\Games\Steam\steamapps\common\Blender\3.6\python\lib\site-packages\numpy\linalg\linalg.py", line 197, in _assert_stacked_2d
    raise LinAlgError('%d-dimensional array given. Array must be '
numpy.linalg.LinAlgError: 0-dimensional array given. Array must be at least two-dimensional
Location: D:\Folders\Games\Steam\steamapps\common\Blender\3.6\scripts\modules\bpy\ops.py:113
```
</details>

**Comment by PavelBlend** [comment]
@SamArtGit у меня работает:
![01](https://github.com/PavelBlend/blender-xray/assets/7983249/52daef0b-3f45-484c-90d5-c269bd6794eb)
Скорее всего использование 3.6 - это не единственное условие, чтобы повторить ошибку. Нужен файл в котором ошибка воспроизводится.

**Comment by SamArtGit** [comment]
Пример кинул в Discord ибо проект в разработке и палить модели не хочется на всеобщее обозрение, потому-что данная проблема наблюдается на моделях именно из проектов прошлых версий Blender. Там несколько мешей не склеенных в один и на этих мешах разные ключи форм с развёртками. В итоге при экспорте бьётся меш, а если нажать Purge в разделе Orphan Data, то вылетает. Хотя проделав подобные манипуляции с разделением меша в отдельные и разными ключами форм на основе модели из оригинала в 3.6, то при экспорте всё работает.

**Comment by PavelBlend** [comment]
@SamArtGit а какие кости нужно редактировать? Ну и на всякий случай: какую арматуру (их там две)? Я у рук, ног, глаз прокликал Fit Shape и всё работает. Может там одна кость выдаёт ошибку, а не все?

**Comment by PavelBlend** [comment]
@SamArtGit воспроизвёл ошибку. Нужно, чтобы на кость была привязана одна вершина. Ошибка есть во всех версиях блендера.

**Comment by PavelBlend** [comment]
Исправил. Теперь для одной вершины аддон будет создавать шейп с размером по-умолчанию в 2x2x2 метра, так как габариты точки невозможно определить:
![01](https://github.com/PavelBlend/blender-xray/assets/7983249/04921865-c365-46be-8a61-c9484680bfa3)

**Comment by SamArtGit** [comment]
Извиняюсь, закрутился. Да? Проблема была в этом? Удивительно, не знал что есть кость с одной вершиной в меше, стараюсь чтобы не было таких мусорных/не полноценных привязок. К слову, проверьте ещё экспорт и повторный импорт в .object с формами костей (на примере модели в скафандре), а то там почему-то после экспорта какая-то крокозябра с геометрией на 3.6.

**Comment by PavelBlend** [comment]
@SamArtGit у тебя у объекта головы есть модификатор `Vertex Weight Mix`, из-за которого меш кривой. Примени модификатор и в 3д окне модель испортится. То ли модификатор не правильно настроен, или может баг блендера. Если его удалить, то экспорт без ошибок будет. Если не удалять, то во время экспорта у меня блендер вылетает. И после применения его, начинаю крутить вьюпорт и блендер тоже вылетает.
