### ISSUE TITLE
Не работает импорт в 4.0.

### ISSUE THREAD

**Issue by SamArtGit** [PavelBlend/blender-xray#708]
Новая версия, новые ошибки. Каждый раз одно и тоже. %)

<details>
  <summary></summary>

![image](https://github.com/PavelBlend/blender-xray/assets/56885075/96446fb8-0d70-469d-b6a8-207e62c030ca)

<details>
  <summary></summary>
Python: Traceback (most recent call last):
  File "C:\Users\artem\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\log.py", line 281, in wrapper
    return method(self, context)
  File "C:\Users\artem\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\utils\stats.py", line 277, in wrapper
    result = method(self, context)
  File "C:\Users\artem\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\utils\ie.py", line 70, in wrapper
    result = method(self, context, *args)
  File "C:\Users\artem\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\formats\obj\imp\ops.py", line 68, in execute
    utils.ie.import_files(
  File "C:\Users\artem\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\utils\ie.py", line 200, in import_files
    report_errors(context)
  File "C:\Users\artem\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\utils\ie.py", line 215, in report_errors
    raise first_error
  File "C:\Users\artem\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\utils\ie.py", line 191, in import_files
    result = imp_fun(file_path, context)
  File "C:\Users\artem\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\log.py", line 267, in wrap
    return func(*args, **kwargs)
  File "C:\Users\artem\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\utils\stats.py", line 238, in wrapper
    result = method(*args, **kwargs)
  File "C:\Users\artem\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\formats\obj\imp\main.py", line 138, in import_file
    bpy_material, bpy_image = utils.material.get_material(
  File "C:\Users\artem\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\utils\material.py", line 336, in get_material
    bpy_material, bpy_image = _create_material_and_image(
  File "C:\Users\artem\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\utils\material.py", line 290, in _create_material_and_image
    princ_node = create_mat_nodes(bpy_material)
  File "C:\Users\artem\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\utils\material.py", line 183, in create_mat_nodes
    princ_node.inputs['Specular'].default_value = 0.0
KeyError: 'bpy_prop_collection[key]: key "Specular" not found'
</details>

</details>

**Comment by PavelBlend** [comment]
@SamArtGit у меня 4.0 не запускается:
![01](https://github.com/PavelBlend/blender-xray/assets/7983249/c1a677f9-d434-4fd0-879a-22441d0ae95c)

Видеокарта старая. Я не смогу править аддон под 4.0.

Сейчас последняя версия блендера, на которой будет работать аддон, это 3.6. Но импорт уровней будет работать в 3.4 (#622). Так что лучше использовать 3.4, пока 3.6 не пофиксили.

**Comment by SamArtGit** [comment]
Получается даже импорт .object работать не будет?

**Comment by PavelBlend** [comment]
@SamArtGit в 4.0? Не знаю, не проверял. В 3.6 импорт object должен работать.

**Comment by s30-zip** [comment]
@PavelBlend, а если сборку blender4.0 для win7 попробовать запустить? У меня на nvidia 610 запускается.

**Comment by SamArtGit** [comment]
@s30-zip +. Но разве не дело в видеокарте? У Павла Win 10, судя по видео.
@PavelBlend на всякий случай: https://github.com/nalexandru/BlenderCompat/releases/tag/4.0.0.

**Comment by PavelBlend** [comment]
У меня цп со встроенной графикой устарел. Последние драйвера вышли в 2015. Минимальные требования блендера говорят, что архитектура должна быть GCN 1-го поколения и новее:
https://www.blender.org/download/requirements/#graphics-cards

У меня TeraScale 3.

Проблемы с блендером начались ещё с версий 2.8x-2.9x. Были артефакты у системы частиц, в полноэкранных окнах, у мешей в 3д окне. На 4.0 моя карта окончательно устарела.

**Comment by TheParaziT** [comment]
А если открыть донаты? Я бы подкинул, сколько смог

**Comment by PavelBlend** [comment]
@TheParaziT я могу сам бу купить. Какую-нибудь 1080. Или около того. До этого нужды особой не было. Те артефакты не критичные. А в игры я не играю. И в блендере много не моделирую.
