### ISSUE TITLE
Import .object and .ogf incompatible with Blender 4.0

### ISSUE THREAD

**Issue by Blackgrowl** [PavelBlend/blender-xray#714]
Greetings.

After the Blender 4.0 update, PavelBlend 2.33.1 still works but when importing or exporting as .object or .ogf, there will be many error reports.

I am very sure the reason why is because PavelBlend still uses the old Principled BSDF and "Bone Groups".
1. The Principled BSDF has been updated, namely for PavelBlend there's no longer a Specular, it has been renamed to "IOR Level".
2. Bone Groups have been replaced with Bone Layers/Collection instead.

This is an error that appears when I import an .ogf
```python
Python: Traceback (most recent call last):
  File "C:\Users\TheSa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\log.py", line 281, in wrapper
    return method(self, context)
  File "C:\Users\TheSa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\utils\stats.py", line 277, in wrapper
    result = method(self, context)
  File "C:\Users\TheSa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\utils\ie.py", line 70, in wrapper
    result = method(self, context, *args)
  File "C:\Users\TheSa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\formats\ogf\imp\ops.py", line 88, in execute
    utils.ie.import_files(
  File "C:\Users\TheSa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\utils\ie.py", line 200, in import_files
    report_errors(context)
  File "C:\Users\TheSa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\utils\ie.py", line 215, in report_errors
    raise first_error
  File "C:\Users\TheSa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\utils\ie.py", line 191, in import_files
    result = imp_fun(file_path, context)
  File "C:\Users\TheSa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\log.py", line 267, in wrap
    return func(*args, **kwargs)
  File "C:\Users\TheSa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\utils\stats.py", line 238, in wrapper
    result = method(*args, **kwargs)
  File "C:\Users\TheSa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\formats\ogf\imp\main.py", line 117, in import_file
    import_ogf_visual(context, data, visual)
  File "C:\Users\TheSa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\formats\ogf\imp\main.py", line 61, in import_ogf_visual
    import_fun(context, chunks, ogf_chunks, visual)
  File "C:\Users\TheSa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\formats\ogf\imp\load.py", line 79, in read_mt_skeleton_anim
    read_mt_skeleton_rigid(context, chunks, ogf_chunks, visual)
  File "C:\Users\TheSa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\formats\ogf\imp\load.py", line 74, in read_mt_skeleton_rigid
    child.import_children(context, chunks, ogf_chunks, visual)
  File "C:\Users\TheSa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\formats\ogf\imp\child.py", line 58, in import_children
    main.import_ogf_visual(context, child_data, visual)
  File "C:\Users\TheSa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\formats\ogf\imp\main.py", line 61, in import_ogf_visual
    import_fun(context, chunks, ogf_chunks, visual)
  File "C:\Users\TheSa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\formats\ogf\imp\load.py", line 90, in read_mt_skeleton_geom_def_pm
    read_mt_skeleton_geom_def_st(context, chunks, ogf_chunks, visual)
  File "C:\Users\TheSa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\formats\ogf\imp\load.py", line 84, in read_mt_skeleton_geom_def_st
    shader.read_texture(context, chunks, ogf_chunks, visual)
  File "C:\Users\TheSa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\formats\ogf\imp\shader.py", line 25, in read_texture
    bpy_material, bpy_image = utils.material.get_material(
  File "C:\Users\TheSa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\utils\material.py", line 336, in get_material
    bpy_material, bpy_image = _create_material_and_image(
  File "C:\Users\TheSa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\utils\material.py", line 290, in _create_material_and_image
    princ_node = create_mat_nodes(bpy_material)
  File "C:\Users\TheSa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\utils\material.py", line 183, in create_mat_nodes
    princ_node.inputs['Specular'].default_value = 0.0
KeyError: 'bpy_prop_collection[key]: key "Specular" not found'
bpy.ops.xray_import.ogf(filepath="G:\\X-Ray Engine SDK\\AXRToolset\\OUTPUT\\AnomalyLATEST\\meshes\\actors\\stalker_neutral\\stalker_neutral_2.ogf", directory="G:\\X-Ray Engine SDK\\AXRToolset\\OUTPUT\\AnomalyLATEST\\meshes\\actors\\stalker_neutral\\", files=[{"name":"stalker_neutral_2.ogf", "name":"stalker_neutral_2.ogf"}], import_motions=False, processed=False)
```

This is an error that appears when I import an .object, it seems that the issue is equal to the .ogf itself:
```python
Python: Traceback (most recent call last):
  File "C:\Users\TheSa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\log.py", line 281, in wrapper
    return method(self, context)
  File "C:\Users\TheSa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\utils\stats.py", line 277, in wrapper
    result = method(self, context)
  File "C:\Users\TheSa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\utils\ie.py", line 70, in wrapper
    result = method(self, context, *args)
  File "C:\Users\TheSa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\formats\obj\imp\ops.py", line 68, in execute
    utils.ie.import_files(
  File "C:\Users\TheSa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\utils\ie.py", line 200, in import_files
    report_errors(context)
  File "C:\Users\TheSa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\utils\ie.py", line 215, in report_errors
    raise first_error
  File "C:\Users\TheSa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\utils\ie.py", line 191, in import_files
    result = imp_fun(file_path, context)
  File "C:\Users\TheSa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\log.py", line 267, in wrap
    return func(*args, **kwargs)
  File "C:\Users\TheSa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\utils\stats.py", line 238, in wrapper
    result = method(*args, **kwargs)
  File "C:\Users\TheSa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\formats\obj\imp\main.py", line 138, in import_file
    bpy_material, bpy_image = utils.material.get_material(
  File "C:\Users\TheSa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\utils\material.py", line 336, in get_material
    bpy_material, bpy_image = _create_material_and_image(
  File "C:\Users\TheSa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\utils\material.py", line 290, in _create_material_and_image
    princ_node = create_mat_nodes(bpy_material)
  File "C:\Users\TheSa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\utils\material.py", line 183, in create_mat_nodes
    princ_node.inputs['Specular'].default_value = 0.0
KeyError: 'bpy_prop_collection[key]: key "Specular" not found'
```

This is an error that appears when I export a skeleton, with a mesh, as an .object
```python
Python: Traceback (most recent call last):
  File "C:\Users\TheSa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\log.py", line 281, in wrapper
    return method(self, context)
  File "C:\Users\TheSa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\utils\stats.py", line 277, in wrapper
    result = method(self, context)
  File "C:\Users\TheSa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\utils\ie.py", line 70, in wrapper
    result = method(self, context, *args)
  File "C:\Users\TheSa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\formats\obj\exp\ops.py", line 219, in execute
    main.export_file(bpy_obj, self.filepath, export_context)
  File "C:\Users\TheSa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\log.py", line 267, in wrap
    return func(*args, **kwargs)
  File "C:\Users\TheSa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\utils\stats.py", line 238, in wrapper
    result = method(*args, **kwargs)
  File "C:\Users\TheSa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\formats\obj\exp\main.py", line 558, in export_file
    export_body(bpy_obj, writer, context)
  File "C:\Users\TheSa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\formats\obj\exp\main.py", line 547, in export_body
    export_main(bpy_obj, writer, context)
  File "C:\Users\TheSa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\formats\obj\exp\main.py", line 530, in export_main
    materials, bone_writers, some_arm, bpy_root, uv_map_names = export_meshes(
  File "C:\Users\TheSa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_xray\formats\obj\exp\main.py", line 312, in export_meshes
    if len(bpy_arm_obj.pose.bone_groups):
AttributeError: 'Pose' object has no attribute 'bone_groups'
```

(Sorry about the code formatting, I am not sure why it came out badly disorganized like that)

**Comment by SamArtGit** [comment]
#708

**Comment by PavelBlend** [comment]
@Blackgrowl hello. Addon is not supported in blender 4.

> Sorry about the code formatting, I am not sure why it came out badly disorganized like that

you need to use three apostrophes: ` ``` text ``` `
