### ISSUE TITLE
Ошибка skl экспорта, когда невозможно создать папку

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#732]
При batch-skl экспорте, когда создаётся папка для анимаций, появляется ошибка, если имя папки совпадает с именем существующего файла:

```python
Traceback (most recent call last):
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_xray\log.py", line 284, in wrapper
    return method(self, context)
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_xray\utils\stats.py", line 277, in wrapper
    result = method(self, context)
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_xray\utils\ie.py", line 70, in wrapper
    result = method(self, context, *args)
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_xray\formats\skl\ops.py", line 441, in execute
    exp.export_skl_file(filepath, export_context)
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_xray\log.py", line 270, in wrap
    return func(*args, **kwargs)
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_xray\utils\stats.py", line 238, in wrapper
    result = method(*args, **kwargs)
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_xray\formats\skl\exp.py", line 48, in export_skl_file
    rw.utils.save_file(file_path, writer)
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_xray\rw\utils.py", line 54, in save_file
    with open(file_path, 'wb') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Pavel\\Desktop\\New Folder\\stalker_bandit_1.ogf\\norm_2_critical_hit_hend_left_0.skl'
```

Чтобы воспроизвести ошибку, нужно импортировать `*.object` с анимациями, а потом сделать экспорт `*.object` в любую папку и в ту же папку сделать batch-skl экспорт. Экспорт `skl` нужно делать с помощью этого оператора:
![01](https://github.com/PavelBlend/blender-xray/assets/7983249/4ffae2fb-c996-482c-996f-b0efaead3ee4)

**Comment by PavelBlend** [comment]
Теперь будут появляться читаемые ошибки:

![03](https://github.com/PavelBlend/blender-xray/assets/7983249/3b333e8a-4c36-4488-9ad5-2c6a29a8edee)

![02](https://github.com/PavelBlend/blender-xray/assets/7983249/d5fa08e4-cc68-4024-9d14-336c14457e72)
