### ISSUE TITLE
Перестал работать плагин.

### ISSUE THREAD

**Issue by GupiDZ** [PavelBlend/blender-xray#757]
#### Краткое описание проблемы:
При импорте любого объекта появлется ошибка:
`Python: Traceback (most recent call last):
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\io_scene_xray\log.py", line 287, in wrapper
    return method(self, context)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\io_scene_xray\utils\stats.py", line 277, in wrapper
    result = method(self, context)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\io_scene_xray\utils\ie.py", line 56, in wrapper
    result = method(self, context, *args)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\io_scene_xray\formats\level\imp\ops.py", line 73, in execute
    main.import_file(import_context)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\io_scene_xray\log.py", line 273, in wrap
    return func(*args, **kwargs)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\io_scene_xray\utils\stats.py", line 238, in wrapper
    result = method(*args, **kwargs)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\io_scene_xray\formats\level\imp\main.py", line 185, in import_file
    _import_main(imp_ctx, level)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\io_scene_xray\formats\level\imp\main.py", line 143, in _import_main
    header.get_version(level, chunks, context.filepath)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\io_scene_xray\formats\level\imp\header.py", line 9, in get_version
    data = chunks.pop(fmt.HEADER)
KeyError: 1
`
Пробовал разные версии софта и аддона, полностью сносил все - результат один и тот же.

**Comment by PavelBlend** [comment]
@GupiDZ при импорте объекта в формате `*.object`? Если да, то почему в логе указана ошибка `game level` импортёра? Ты пытаешься импортировать `*.object` файлы с помощью `level` импортёра? Вот я то же попробовал и ошибка та же:

```python
Traceback (most recent call last):
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_xray\log.py", line 287, in wrapper
    return method(self, context)
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_xray\utils\stats.py", line 277, in wrapper
    result = method(self, context)
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_xray\utils\ie.py", line 56, in wrapper
    result = method(self, context, *args)
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_xray\formats\level\imp\ops.py", line 73, in execute
    main.import_file(import_context)
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_xray\log.py", line 273, in wrap
    return func(*args, **kwargs)
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_xray\utils\stats.py", line 238, in wrapper
    result = method(*args, **kwargs)
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_xray\formats\level\imp\main.py", line 185, in import_file
    _import_main(imp_ctx, level)
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_xray\formats\level\imp\main.py", line 143, in _import_main
    header.get_version(level, chunks, context.filepath)
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_xray\formats\level\imp\header.py", line 9, in get_version
    data = chunks.pop(fmt.HEADER)
KeyError: 1
```

Для импорта `object` нужно использовать другой оператор:
![01](https://github.com/PavelBlend/blender-xray/assets/7983249/34e7c65c-1116-4556-aeea-da233903a1bf)

**Comment by GupiDZ** [comment]
> @GupiDZ при импорте объекта в формате `*.object`? Если да, то почему в логе указана ошибка `game level` импортёра? Ты пытаешься импортировать `*.object` файлы с помощью `level` импортёра? Вот я то же попробовал и ошибка та же:
> 
> ```python
> Traceback (most recent call last):
>   File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_xray\log.py", line 287, in wrapper
>     return method(self, context)
>   File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_xray\utils\stats.py", line 277, in wrapper
>     result = method(self, context)
>   File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_xray\utils\ie.py", line 56, in wrapper
>     result = method(self, context, *args)
>   File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_xray\formats\level\imp\ops.py", line 73, in execute
>     main.import_file(import_context)
>   File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_xray\log.py", line 273, in wrap
>     return func(*args, **kwargs)
>   File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_xray\utils\stats.py", line 238, in wrapper
>     result = method(*args, **kwargs)
>   File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_xray\formats\level\imp\main.py", line 185, in import_file
>     _import_main(imp_ctx, level)
>   File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_xray\formats\level\imp\main.py", line 143, in _import_main
>     header.get_version(level, chunks, context.filepath)
>   File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_xray\formats\level\imp\header.py", line 9, in get_version
>     data = chunks.pop(fmt.HEADER)
> KeyError: 1
> ```
> 
> Для импорта `object` нужно использовать другой оператор: ![01](https://private-user-images.githubusercontent.com/7983249/316237090-34e7c65c-1116-4556-aeea-da233903a1bf.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExOTMwMTQsIm5iZiI6MTcxMTE5MjcxNCwicGF0aCI6Ii83OTgzMjQ5LzMxNjIzNzA5MC0zNGU3YzY1Yy0xMTE2LTQ1NTYtYWVlYS1kYTIzMzkwM2ExYmYuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjNUMTExODM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2U1ODVkNjc5YTk3NmRlN2Y3MGM4YWY4YWE2NDMyNGJkNWQ3NWYwMzRiNjExODliZTJjOWNlYTJkNDllNTkzYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.g5BkGsgasAEzDHbDFKTQV9f6y5I9nCZCaVAYHkNF7Ro)

Нет, я в пытаюсь открыть level

**Comment by GupiDZ** [comment]
`Python: Traceback (most recent call last):
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\io_scene_xray\log.py", line 287, in wrapper
    return method(self, context)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\io_scene_xray\utils\stats.py", line 277, in wrapper
    result = method(self, context)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\io_scene_xray\utils\ie.py", line 56, in wrapper
    result = method(self, context, *args)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\io_scene_xray\formats\obj\imp\ops.py", line 68, in execute
    utils.ie.import_files(
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\io_scene_xray\utils\ie.py", line 186, in import_files
    report_errors(context)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\io_scene_xray\utils\ie.py", line 201, in report_errors
    raise first_error
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\io_scene_xray\utils\ie.py", line 177, in import_files
    result = imp_fun(file_path, context)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\io_scene_xray\log.py", line 273, in wrap
    return func(*args, **kwargs)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\io_scene_xray\utils\stats.py", line 238, in wrapper
    result = method(*args, **kwargs)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\io_scene_xray\formats\obj\imp\main.py", line 138, in import_file
    bpy_material, bpy_image = utils.material.get_material(
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\io_scene_xray\utils\material.py", line 336, in get_material
    bpy_material, bpy_image = _create_material_and_image(
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\io_scene_xray\utils\material.py", line 290, in _create_material_and_image
    princ_node = create_mat_nodes(bpy_material)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\io_scene_xray\utils\material.py", line 183, in create_mat_nodes
    princ_node.inputs['Specular'].default_value = 0.0
KeyError: 'bpy_prop_collection[key]: key "Specular" not found'
`

Вот с твоим способом, пытаюсь открыть *.object

**Comment by Max1m1661** [comment]
Blender 4.0?

> `Python: Traceback (most recent call last): File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\io_scene_xray\log.py", line 287, in wrapper return method(self, context) File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\io_scene_xray\utils\stats.py", line 277, in wrapper result = method(self, context) File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\io_scene_xray\utils\ie.py", line 56, in wrapper result = method(self, context, *args) File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\io_scene_xray\formats\obj\imp\ops.py", line 68, in execute utils.ie.import_files( File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\io_scene_xray\utils\ie.py", line 186, in import_files report_errors(context) File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\io_scene_xray\utils\ie.py", line 201, in report_errors raise first_error File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\io_scene_xray\utils\ie.py", line 177, in import_files result = imp_fun(file_path, context) File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\io_scene_xray\log.py", line 273, in wrap return func(*args, **kwargs) File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\io_scene_xray\utils\stats.py", line 238, in wrapper result = method(*args, **kwargs) File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\io_scene_xray\formats\obj\imp\main.py", line 138, in import_file bpy_material, bpy_image = utils.material.get_material( File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\io_scene_xray\utils\material.py", line 336, in get_material bpy_material, bpy_image = _create_material_and_image( File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\io_scene_xray\utils\material.py", line 290, in _create_material_and_image princ_node = create_mat_nodes(bpy_material) File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\io_scene_xray\utils\material.py", line 183, in create_mat_nodes princ_node.inputs['Specular'].default_value = 0.0 KeyError: 'bpy_prop_collection[key]: key "Specular" not found' `
> 
> Вот с твоим способом, пытаюсь открыть *.object

**Comment by GupiDZ** [comment]
> Blender 4.0?
> 
> > `Python: Traceback (most recent call last): File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\io_scene_xray\log.py", line 287, in wrapper return method(self, context) File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\io_scene_xray\utils\stats.py", line 277, in wrapper result = method(self, context) File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\io_scene_xray\utils\ie.py", line 56, in wrapper result = method(self, context, *args) File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\io_scene_xray\formats\obj\imp\ops.py", line 68, in execute utils.ie.import_files( File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\io_scene_xray\utils\ie.py", line 186, in import_files report_errors(context) File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\io_scene_xray\utils\ie.py", line 201, in report_errors raise first_error File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\io_scene_xray\utils\ie.py", line 177, in import_files result = imp_fun(file_path, context) File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\io_scene_xray\log.py", line 273, in wrap return func(*args, **kwargs) File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\io_scene_xray\utils\stats.py", line 238, in wrapper result = method(*args, **kwargs) File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\io_scene_xray\formats\obj\imp\main.py", line 138, in import_file bpy_material, bpy_image = utils.material.get_material( File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\io_scene_xray\utils\material.py", line 336, in get_material bpy_material, bpy_image = _create_material_and_image( File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\io_scene_xray\utils\material.py", line 290, in _create_material_and_image princ_node = create_mat_nodes(bpy_material) File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\io_scene_xray\utils\material.py", line 183, in create_mat_nodes princ_node.inputs['Specular'].default_value = 0.0 KeyError: 'bpy_prop_collection[key]: key "Specular" not found' `
> > Вот с твоим способом, пытаюсь открыть *.object

в данный момент, да. Буквально час назад стоял 3.6 - была та же песня.

**Comment by PavelBlend** [comment]
> Нет, я в пытаюсь открыть level

level из какой папки? Из rawdata\maps? Нужно из gamedata\levels скомпилированные локации импортировать.

**Comment by PavelBlend** [comment]
> key "Specular" not found

эта ошибка может быть только в 4,0 и выше. Аддон не поддерживается в них. Самая новая версия блендера для аддона - это 3,6. Аддон желательно обновить до последней версии, если ещё не обновлен.

**Comment by PavelBlend** [comment]
Получилось импортировать? Если нет, то откроешь заново эту issue. Я пока здесь проблемы не вижу, так как ошибка из-за неправильного формата.

**Comment by AbsoluteMikhail** [comment]
> > key "Specular" not found
> 
> эта ошибка может быть только в 4,0 и выше. Аддон не поддерживается в них. Самая новая версия блендера для аддона - это 3,6. Аддон желательно обновить до последней версии, если ещё не обновлен.

а можно в редми или вики указать что с 4 блендером плагин не работает =(

**Comment by PavelBlend** [comment]
> а можно в редми или вики указать что с 4 блендером плагин не работает =(

в вики указаны поддерживаемые версии:
[Поддерживаемые версии Blender](https://github.com/PavelBlend/blender-xray/wiki/Download#%D0%BF%D0%BE%D0%B4%D0%B4%D0%B5%D1%80%D0%B6%D0%B8%D0%B2%D0%B0%D0%B5%D0%BC%D1%8B%D0%B5-%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D0%B8-blender)
