### ISSUE TITLE
invalid euler order 'QUATERNION'

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#76]
При попытке экспортировать объект с анимациями плагин выдаёт ошибку:

Traceback (most recent call last):
  File "C:\Program Project\Blender 2.77a\2.77\scripts\addons\io_scene_xray\plugin.py", line 198, in execute
    export_file(context.scene.objects[self.object], self.filepath, cx)
  File "C:\Program Project\Blender 2.77a\2.77\scripts\addons\io_scene_xray\fmt_object_exp.py", line 359, in export_file
    _export(bpy_obj, cw, cx)
  File "C:\Program Project\Blender 2.77a\2.77\scripts\addons\io_scene_xray\fmt_object_exp.py", line 352, in _export
    _export_main(bpy_obj, w, cx)
  File "C:\Program Project\Blender 2.77a\2.77\scripts\addons\io_scene_xray\fmt_object_exp.py", line 330, in _export_main
    export_motions(pw, a, cx, some_arm)
  File "C:\Program Project\Blender 2.77a\2.77\scripts\addons\io_scene_xray\xray_motions.py", line 40, in export_motions
    mat = xm \* Matrix.Translation(tr) \* Euler(rt, rotmode).to_matrix().to_4x4()
ValueError: mathutils.Euler(): invalid euler order 'QUATERNION'

Это связано с тем, что у кости стоит не правильный режим вращения. Как изменить режим вращения у всех нужных костей так, чтобы анимация сохранилась такой как есть? Вот пример: [rotation_mode.zip](https://github.com/igelbox/blender-xray/files/253979/rotation_mode.zip)
Так получилось, что в сцене кости имеют разные режимы вращения, и это заметил я слишком поздно.

**Comment by igelbox** [comment]
ОК. Давай сделаем warning и преобразование.

**Comment by PavelBlend** [comment]
Давай. А на данный момент какой режим ротации нужно использовать?

**Comment by igelbox** [comment]
Тот, с которым сам плагин импортирует кости, т.е. `ZXY Euler`

**Comment by igelbox** [comment]
Теперь можно использовать все режимы вращения костей, кроме `Axis Angle`.
А также пропускать кривые анимации в группах (взамен будет писаться 0) и менять их порядок в группах.
Warning-и сделал только на мусорные кривые (т.е. например если встретилась кривая .rotation_euler, а режим вращения = `Quaternion`)
