### ISSUE TITLE
Не работает импорт моделей.

### ISSUE THREAD

**Issue by vladvexa** [PavelBlend/blender-xray#795]
Не знаю почему не импортируются какие-либо модели, выходит только такой результат:

![изображение_2024-09-02_084248088](https://github.com/user-attachments/assets/6dd484d0-6087-4713-8248-2b14c1269972)

И вот такой лог ошибок:

Python: Traceback (most recent call last):
  File "C:\Users\Влад\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_scene_xray\log.py", line 289, in wrapper
    return method(self, context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Влад\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_scene_xray\utils\stats.py", line 285, in wrapper
    result = method(self, context)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Влад\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_scene_xray\utils\ie.py", line 57, in wrapper
    result = method(self, context, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Влад\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_scene_xray\formats\ogf\imp\ops.py", line 88, in execute
    utils.ie.import_files(
  File "C:\Users\Влад\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_scene_xray\utils\ie.py", line 187, in import_files
    report_errors(context)
  File "C:\Users\Влад\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_scene_xray\utils\ie.py", line 202, in report_errors
    raise first_error
  File "C:\Users\Влад\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_scene_xray\utils\ie.py", line 178, in import_files
    result = imp_fun(file_path, context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Влад\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_scene_xray\log.py", line 275, in wrap
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Влад\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_scene_xray\utils\stats.py", line 246, in wrapper
    result = method(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Влад\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_scene_xray\formats\ogf\imp\main.py", line 120, in import_file
    import_ogf_visual(context, data, visual)
  File "C:\Users\Влад\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_scene_xray\formats\ogf\imp\main.py", line 61, in import_ogf_visual
    import_fun(context, chunks, ogf_chunks, visual)
  File "C:\Users\Влад\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_scene_xray\formats\ogf\imp\load.py", line 79, in read_mt_skeleton_anim
    read_mt_skeleton_rigid(context, chunks, ogf_chunks, visual)
  File "C:\Users\Влад\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_scene_xray\formats\ogf\imp\load.py", line 74, in read_mt_skeleton_rigid
    child.import_children(context, chunks, ogf_chunks, visual)
  File "C:\Users\Влад\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_scene_xray\formats\ogf\imp\child.py", line 58, in import_children
    main.import_ogf_visual(context, child_data, visual)
  File "C:\Users\Влад\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_scene_xray\formats\ogf\imp\main.py", line 61, in import_ogf_visual
    import_fun(context, chunks, ogf_chunks, visual)
  File "C:\Users\Влад\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_scene_xray\formats\ogf\imp\load.py", line 90, in read_mt_skeleton_geom_def_pm
    read_mt_skeleton_geom_def_st(context, chunks, ogf_chunks, visual)
  File "C:\Users\Влад\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_scene_xray\formats\ogf\imp\load.py", line 84, in read_mt_skeleton_geom_def_st
    shader.read_texture(context, chunks, ogf_chunks, visual)
  File "C:\Users\Влад\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_scene_xray\formats\ogf\imp\shader.py", line 25, in read_texture
    bpy_material, bpy_image = utils.material.get_material(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Влад\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_scene_xray\utils\material.py", line 336, in get_material
    bpy_material, bpy_image = _create_material_and_image(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Влад\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_scene_xray\utils\material.py", line 290, in _create_material_and_image
    princ_node = create_mat_nodes(bpy_material)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Влад\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_scene_xray\utils\material.py", line 183, in create_mat_nodes
    princ_node.inputs['Specular'].default_value = 0.0
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'bpy_prop_collection[key]: key "Specular" not found'
bpy.ops.xray_import.ogf(filepath="D:\\X-Ray_CoP_SDK\\editors\\gamedata\\meshes\\actors\\stalker_neutral\\stalker_neutral_1.ogf", directory="D:\\X-Ray_CoP_SDK\\editors\\gamedata\\meshes\\actors\\stalker_neutral\\", files=[{"name":"stalker_neutral_1.ogf", "name":"stalker_neutral_1.ogf"}], import_motions=True, processed=False)

**Comment by PavelBlend** [comment]
@vladvexa у тебя блендер 4.2. А он на данный момент не поддерживается: #715 
Последняя версия, в которой аддон работает - это 3.6.
