### ISSUE TITLE
IndexError: BMElemSeq[index]: index 5643 out of range

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#80]
Этот файл не импортируется: [trash_zil_130_1_lod.zip](https://github.com/igelbox/blender-xray/files/260071/trash_zil_130_1_lod.zip)
Выдаётся ошибка:

```
Traceback (most recent call last):
  File "C:\Program Project\Blender 2.77a\2.77\scripts\addons\io_scene_xray\plugin.py", line 63, in execute
    import_file(self.directory + file.name, cx)
  File "C:\Program Project\Blender 2.77a\2.77\scripts\addons\io_scene_xray\fmt_object_imp.py", line 595, in import_file
    _import(fpath, cx, ChunkedReader(f.read()))
  File "C:\Program Project\Blender 2.77a\2.77\scripts\addons\io_scene_xray\fmt_object_imp.py", line 588, in _import
    _import_main(fpath, cx, ChunkedReader(data))
  File "C:\Program Project\Blender 2.77a\2.77\scripts\addons\io_scene_xray\fmt_object_imp.py", line 325, in _import_main
    meshes.append(_import_mesh(cx, ChunkedReader(mdat), bpy_obj))
  File "C:\Program Project\Blender 2.77a\2.77\scripts\addons\io_scene_xray\fmt_object_imp.py", line 168, in _import_mesh
    for l in bm.verts[vi].link_loops:
IndexError: BMElemSeq[index]: index 5643 out of range

location: <unknown location>:-1
```

**Comment by igelbox** [comment]
В vmaps-ах были ссылки на не существующие вертексы.
Сделал поддержку VMREFS-чанка и теперь использую ссылки на вертексы из него.
Надо бы проверить, что не сломалась загрузка други моделей, которые раньше нормально грузились (ошибки, съехавшие uv-координаты, съехавшие веса).

**Comment by PavelBlend** [comment]
На этой модели неправильные текстурные координаты (на самом пистолете)
[wpn_colt1911_hud.zip](https://github.com/igelbox/blender-xray/files/276407/wpn_colt1911_hud.2.zip)
А можно ли в исходниках сдк посмотреть, как загружается юви, и сделать тоже самое в плагине?

**Comment by igelbox** [comment]
Хорошо, что заметил. Это из-за рассинхронизации при пропуске треугольников. Поправил.
Я посмотрел: в исходниках SDK - примерно такой же алгоритм (бежит по треугольникам и для каждой точки треугольника смотрит её vmrefs-ы и для каждого vmrefs-а решает что настраивать - uv или weight).
