### ISSUE TITLE
Улучшение в XRay Engine Object -> Motions -> Dependency

### ISSUE THREAD

**Issue by TheParaziT** [PavelBlend/blender-xray#819]
#### Описание идеи:
При выборе не арматуры в Dependency в Motions выдается ошибка. Позволить выбирать в этом поле только арматуру, либо выводить читаемое предупреждение

#### Примеры использования:
Экспорт без затупов

**Comment by PavelBlend** [comment]
Такая ошибка возникает? Она может возникнуть, даже если объект является арматурой.
```python
Python: Traceback (most recent call last):
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_xray\log.py", line 289, in wrapper
    return method(self, context)
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_xray\utils\stats.py", line 285, in wrapper
    result = method(self, context)
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_xray\utils\ie.py", line 57, in wrapper
    result = method(self, context, *args)
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_xray\formats\obj\exp\ops.py", line 219, in execute
    main.export_file(bpy_obj, export_context)
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_xray\log.py", line 275, in wrap
    return func(*args, **kwargs)
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_xray\utils\stats.py", line 246, in wrapper
    result = method(*args, **kwargs)
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_xray\formats\obj\exp\main.py", line 555, in export_file
    ObjectExporter(root_obj, context)
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_xray\formats\obj\exp\main.py", line 32, in __init__
    self.export()
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_xray\formats\obj\exp\main.py", line 36, in export
    self.export_body()
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_xray\formats\obj\exp\main.py", line 45, in export_body
    self.export_main()
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_xray\formats\obj\exp\main.py", line 55, in export_main
    self.export_motions()
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_xray\formats\obj\exp\main.py", line 244, in export_motions
    motions.exp.export_motions(
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_xray\utils\action.py", line 80, in wrapper
    frame, mode, act, dep_obj, dep_act = _get_initial_state(arm_obj)
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_xray\utils\action.py", line 65, in _get_initial_state
    dependency_object, dep_action = get_dep_obj(arm_obj)
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_xray\utils\action.py", line 20, in get_dep_obj
    dep_action = dependency_object.animation_data.action
AttributeError: 'NoneType' object has no attribute 'action'
```

Я попробую сделать так, чтобы можно было выбирать только арматуру, но ошибка связана не с этим (если конечно это та ошибка). Для ошибки я открыл новую задачу #820

**Comment by PavelBlend** [comment]
@TheParaziT Хотя я подумал. Может не стоит делать такое ограничение, чтобы только арматуры использовать в этом параметре? У меня возникла идея, когда можно пустышку использовать. Я создал пустышку (можно хоть меш, хоть лампу создать и т. д.) и добавил ей кастомное свойство. Это свойство я проанимировал так, чтобы ключи добавились в анимацию `reload`. В итоге получил такой результат (анимация не реальная, а для примера):

https://github.com/user-attachments/assets/f96efe33-191e-4d8a-b17e-9b1466fd0ddb

Констрейнты у костей оружия имеют драйвера, которые управляются кастомным свойством пустышки.

В общем это я к тому, может не нужно делать ограничение на арматуры? Пусть будет возможность указать любой объект. Я ошибки исправил, теперь при экспорте их нет. Так что смысла ограничивать параметр нет.

**Comment by TheParaziT** [comment]
Ну окей, у меня проблема то только из-за ошибки возникала

**Comment by PavelBlend** [comment]
Я просто ещё не хочу менять этот параметр из-за обратной совместимости. Сейчас этот параметр строковый, а нужно сделать pointer (указатель на объект). Если я переделаю, то сломаются файлы, которые сохранены в старой версии аддона. Придётся писать костыль, который будет делать корректное открытие старых файлов. Вроде бы сейчас вреда нет от того, что объекты любые, так что и острой необходимости переписывать нет. Не хочется без крайней нужны костыли писать.
