### ISSUE TITLE
KeyError: key "Bip01" not found

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#83]
При импорте анимации в этом файле ([wpn_colt1911_hud.zip](https://github.com/igelbox/blender-xray/files/261633/wpn_colt1911_hud.zip)) возникает ошибка.

```
Traceback (most recent call last):
  File "C:\Program Project\Blender 2.77a\2.77\scripts\addons\io_scene_xray\plugin.py", line 63, in execute
    import_file(self.directory + file.name, cx)
  File "C:\Program Project\Blender 2.77a\2.77\scripts\addons\io_scene_xray\fmt_object_imp.py", line 599, in import_file
    _import(fpath, cx, ChunkedReader(f.read()))
  File "C:\Program Project\Blender 2.77a\2.77\scripts\addons\io_scene_xray\fmt_object_imp.py", line 592, in _import
    _import_main(fpath, cx, ChunkedReader(data))
  File "C:\Program Project\Blender 2.77a\2.77\scripts\addons\io_scene_xray\fmt_object_imp.py", line 556, in _import_main
    bpy_bone = bpy_armature.bones[bname]
KeyError: 'bpy_prop_collection[key]: key "Bip01" not found'

location: <unknown location>:-1
```

Как я понял, это говорит о том, что есть ключи анимаций для несуществующей кости.

**Comment by igelbox** [comment]
Это опять проблема с регистром символов.
Но, т.к. SDK импортирует без ошибок, то плагину тоже придётся как-то более умно искать кости (например без учёта регистра).
