### ISSUE TITLE
Ошибка: F-кривая «temp[0]» уже существует для действия «draw»

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#86]
При импорте этого object'а [wpn_fort_hud.zip](https://github.com/igelbox/blender-xray/files/288035/wpn_fort_hud.zip) возникает ошибка:

``` python
Traceback (most recent call last):
  File "C:\Program Project\Blender 2.77a\2.77\scripts\addons\io_scene_xray\plugin.py", line 63, in execute
    import_file(self.directory + file.name, cx)
  File "C:\Program Project\Blender 2.77a\2.77\scripts\addons\io_scene_xray\fmt_object_imp.py", line 625, in import_file
    _import(fpath, cx, ChunkedReader(f.read()))
  File "C:\Program Project\Blender 2.77a\2.77\scripts\addons\io_scene_xray\fmt_object_imp.py", line 618, in _import
    _import_main(fpath, cx, ChunkedReader(data))
  File "C:\Program Project\Blender 2.77a\2.77\scripts\addons\io_scene_xray\fmt_object_imp.py", line 540, in _import_main
    tmpfc = [a.fcurves.new('temp', i) for i in range(6)]
  File "C:\Program Project\Blender 2.77a\2.77\scripts\addons\io_scene_xray\fmt_object_imp.py", line 540, in <listcomp>
    tmpfc = [a.fcurves.new('temp', i) for i in range(6)]
RuntimeError: Ошибка: F-кривая «temp[0]» уже существует для действия «draw»


location: <unknown location>:-1
```

**Comment by igelbox** [comment]
Этот объект всё-равно не будет хорошо импортироваться, т.к. MOTIONS-ы ссылаются на несуществующие кости. SDK его тоже импортирует криво.
Откуда он такой взялся?

**Comment by PavelBlend** [comment]
Это модель из слива исходников от GSC.
