### ISSUE TITLE
local variable 'bpy_arm_obj' referenced before assignment

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#87]
Возникает ошибка при импорте [wpn_test.zip](https://github.com/igelbox/blender-xray/files/288029/wpn_test.zip)

```
Traceback (most recent call last):
  File "C:\Program Project\Blender 2.77a\2.77\scripts\addons\io_scene_xray\plugin.py", line 63, in execute
    import_file(self.directory + file.name, cx)
  File "C:\Program Project\Blender 2.77a\2.77\scripts\addons\io_scene_xray\fmt_object_imp.py", line 625, in import_file
    try:
  File "C:\Program Project\Blender 2.77a\2.77\scripts\addons\io_scene_xray\fmt_object_imp.py", line 618, in _import
    _import_main(fpath, cx, ChunkedReader(data))
  File "C:\Program Project\Blender 2.77a\2.77\scripts\addons\io_scene_xray\fmt_object_imp.py", line 501, in _import_main
    cx.bpy.context.scene.objects.active = bpy_arm_obj
UnboundLocalError: local variable 'bpy_arm_obj' referenced before assignment

location: <unknown location>:-1
```

**Comment by igelbox** [comment]
fixed as #85 in 0594f83e8d3e53aec9e9e6e0e04b023ac48483c9
